### ISSUE TITLE
Ingest new metadata produced by new set of tests

### ISSUE THREAD

**Issue by hellais** [ooni/pipeline#202]
This is a master ticket for all feature extractors related to current and future tests:

* [x] Add support for extracting features related to IM tests #200
* [x] Add support for extracting middlebox test features #201 
* [x] Document writing feature extractors for new tests #133

**Comment by hellais** [comment]
We have concluded that this is going to be done inside of the fastpath, work for this has been done in the following PRs and branches:
https://github.com/ooni/pipeline/pull/243
https://github.com/ooni/pipeline/pull/242

cc @FedericoCeratto

**Comment by hellais** [comment]
This is done.
